name: BkTeleport
version: ${project.version}
main: me.bkrmt.bkteleport.BkTeleport
api-version: 1.13
softdepend:
  - Multiverse-Core*
  - Multiverse-Core
  - MultiWorld
  - WorldManager
  - PlaceholderAPI
authors: [Bkr__]
description: 'Replacement for essentials teleport'